	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
	<script src="<?=templates('lib/wow/wow.min.js','website')?>"></script>
  <script src="<?=templates('lib/easing/easing.min.js','website')?>"></script>
  <script src="<?=templates('lib/waypoints/waypoints.min.js','website')?>"></script>
  <script src="<?=templates('lib/owlcarousel/owl.carousel.min.js','website')?>"></script>
  <script src="<?=templates('js/jquery.ajaxchimp.min.js','website')?>"></script>
  <script src="<?=templates('js/mail-script.js','website')?>"></script>
  <script src="<?=templates('js/skrollr.min.js','website')?>"></script>
  <script src="<?=templates('js/main.js','website')?>"></script>
